Traceback (most recent call last):
  File "/home/robot/SEE/EV3_Control.py", line 14, in <module>
  File "ev3dev2/motor.py", line 1873, in __init__
  File "ev3dev2/motor.py", line 1655, in __init__
  File "ev3dev2/motor.py", line 1117, in __init__
  File "ev3dev2/motor.py", line 395, in __init__
  File "ev3dev2/__init__.py", line 223, in __init__
  File "ev3dev2/__init__.py", line 52, in chain_exception
DeviceNotFound: LargeMotor(ev3-ports:outA) is not connected.
